/**
 * Custom MDI iconset: solo los íconos efectivamente usados en templates.
 * Cada ícono se importa por nombre desde @mdi/js (tree-shakeable, ~1KB c/u).
 * El custom iconset de Vuetify resuelve dinámicamente `mdi-name` → SVG path.
 *
 * Para agregar un ícono nuevo:
 *   1. Importarlo aquí desde '@mdi/js'
 *   2. Agregarlo al objeto MDI_ICONS con su nombre kebab-case
 */
import { h } from 'vue'
import type { IconSet, IconProps } from 'vuetify'
import {
  mdiAccount,
  mdiAccountCircle,
  mdiAccountCog,
  mdiAccountGroup,
  mdiAccountPlus,
  mdiAlert,
  mdiAlertCircle,
  mdiArrowLeft,
  mdiArrowUpBold,
  mdiBankTransfer,
  mdiCamera,
  mdiCancel,
  mdiCardAccountDetails,
  mdiCart,
  mdiCartArrowDown,
  mdiCartArrowUp,
  mdiCartOutline,
  mdiCartPlus,
  mdiCash,
  mdiCashMultiple,
  mdiCashRegister,
  mdiChartBar,
  mdiCheck,
  mdiCheckCircle,
  mdiClipboardCheck,
  mdiClockAlert,
  mdiClockOutline,
  mdiClose,
  mdiCloseCircle,
  mdiCog,
  mdiCogOutline,
  mdiContentSave,
  mdiCreditCard,
  mdiCreditCardCheck,
  mdiCrown,
  mdiDelete,
  mdiEmail,
  mdiEye,
  mdiEyeOff,
  mdiFileDocument,
  mdiHelp,
  mdiImage,
  mdiImagePlus,
  mdiLock,
  mdiLockOpen,
  mdiLogout,
  mdiMagnify,
  mdiMapMarker,
  mdiMenuDown,
  mdiNumeric1Circle,
  mdiNumeric2Circle,
  mdiNumeric3Circle,
  mdiPackageVariant,
  mdiPackageVariantClosed,
  mdiPencil,
  mdiPhone,
  mdiPlus,
  mdiPointOfSale,
  mdiQrcode,
  mdiReceipt,
  mdiRefresh,
  mdiRestart,
  mdiShape,
  mdiStore,
  mdiStoreCog,
  mdiStoreOutline,
  mdiStorefrontOutline,
  mdiSwapHorizontal,
  mdiTruck,
  mdiTune,
  mdiViewDashboard,
} from '@mdi/js'

const MDI_ICONS: Record<string, string> = {
  'mdi-account': mdiAccount,
  'mdi-account-circle': mdiAccountCircle,
  'mdi-account-cog': mdiAccountCog,
  'mdi-account-group': mdiAccountGroup,
  'mdi-account-plus': mdiAccountPlus,
  'mdi-alert': mdiAlert,
  'mdi-alert-circle': mdiAlertCircle,
  'mdi-arrow-left': mdiArrowLeft,
  'mdi-arrow-up-bold': mdiArrowUpBold,
  'mdi-bank-transfer': mdiBankTransfer,
  'mdi-camera': mdiCamera,
  'mdi-cancel': mdiCancel,
  'mdi-card-account-details': mdiCardAccountDetails,
  'mdi-cart': mdiCart,
  'mdi-cart-arrow-down': mdiCartArrowDown,
  'mdi-cart-arrow-up': mdiCartArrowUp,
  'mdi-cart-outline': mdiCartOutline,
  'mdi-cart-plus': mdiCartPlus,
  'mdi-cash': mdiCash,
  'mdi-cash-multiple': mdiCashMultiple,
  'mdi-cash-register': mdiCashRegister,
  'mdi-chart-bar': mdiChartBar,
  'mdi-check': mdiCheck,
  'mdi-check-circle': mdiCheckCircle,
  'mdi-clipboard-check': mdiClipboardCheck,
  'mdi-clock-alert': mdiClockAlert,
  'mdi-clock-outline': mdiClockOutline,
  'mdi-close': mdiClose,
  'mdi-close-circle': mdiCloseCircle,
  'mdi-cog': mdiCog,
  'mdi-cog-outline': mdiCogOutline,
  'mdi-content-save': mdiContentSave,
  'mdi-credit-card': mdiCreditCard,
  'mdi-credit-card-check': mdiCreditCardCheck,
  'mdi-crown': mdiCrown,
  'mdi-delete': mdiDelete,
  'mdi-email': mdiEmail,
  'mdi-eye': mdiEye,
  'mdi-eye-off': mdiEyeOff,
  'mdi-file-document': mdiFileDocument,
  'mdi-help': mdiHelp,
  'mdi-image': mdiImage,
  'mdi-image-plus': mdiImagePlus,
  'mdi-lock': mdiLock,
  'mdi-lock-open': mdiLockOpen,
  'mdi-logout': mdiLogout,
  'mdi-magnify': mdiMagnify,
  'mdi-map-marker': mdiMapMarker,
  'mdi-menu-down': mdiMenuDown,
  'mdi-numeric-1-circle': mdiNumeric1Circle,
  'mdi-numeric-2-circle': mdiNumeric2Circle,
  'mdi-numeric-3-circle': mdiNumeric3Circle,
  'mdi-package-variant': mdiPackageVariant,
  'mdi-package-variant-closed': mdiPackageVariantClosed,
  'mdi-pencil': mdiPencil,
  'mdi-phone': mdiPhone,
  'mdi-plus': mdiPlus,
  'mdi-point-of-sale': mdiPointOfSale,
  'mdi-qrcode': mdiQrcode,
  'mdi-receipt': mdiReceipt,
  'mdi-refresh': mdiRefresh,
  'mdi-restart': mdiRestart,
  'mdi-shape': mdiShape,
  'mdi-store': mdiStore,
  'mdi-store-cog': mdiStoreCog,
  'mdi-store-outline': mdiStoreOutline,
  'mdi-storefront-outline': mdiStorefrontOutline,
  'mdi-swap-horizontal': mdiSwapHorizontal,
  'mdi-truck': mdiTruck,
  'mdi-tune': mdiTune,
  'mdi-view-dashboard': mdiViewDashboard,
}

const FALLBACK_PATH = mdiHelp

export const mdiCustomSet: IconSet = {
  component: (props: IconProps) => {
    const raw = String(props.icon ?? '')
    const path = MDI_ICONS[raw] ?? FALLBACK_PATH
    return h(
      'svg',
      {
        class: 'v-icon__svg',
        xmlns: 'http://www.w3.org/2000/svg',
        viewBox: '0 0 24 24',
        role: 'img',
        'aria-hidden': 'true',
      },
      [h('path', { d: path })]
    )
  },
}

export const mdiCustomAliases = {
  // Aliases que Vuetify usa internamente (close, expand, etc.)
  complete: mdiCheck,
  cancel: mdiCloseCircle,
  close: mdiClose,
  delete: mdiCloseCircle,
  clear: mdiCloseCircle,
  success: mdiCheckCircle,
  info: mdiAlertCircle,
  warning: mdiAlert,
  error: mdiAlertCircle,
  prev: mdiArrowLeft,
  next: mdiArrowLeft,
  checkboxOn: mdiCheck,
  checkboxOff: mdiClose,
  checkboxIndeterminate: mdiMenuDown,
  delimiter: mdiCheck,
  sortAsc: mdiArrowUpBold,
  sortDesc: mdiArrowUpBold,
  expand: mdiMenuDown,
  menu: mdiMenuDown,
  subgroup: mdiMenuDown,
  dropdown: mdiMenuDown,
  radioOn: mdiCheckCircle,
  radioOff: mdiCheckCircle,
  edit: mdiPencil,
  ratingEmpty: mdiCheck,
  ratingFull: mdiCheck,
  ratingHalf: mdiCheck,
  loading: mdiRefresh,
  first: mdiArrowLeft,
  last: mdiArrowLeft,
  unfold: mdiMenuDown,
  file: mdiFileDocument,
  plus: mdiPlus,
  minus: mdiClose,
  calendar: mdiClockOutline,
  treeviewCollapse: mdiMenuDown,
  treeviewExpand: mdiMenuDown,
  eyeDropper: mdiEye,
  upload: mdiArrowUpBold,
  color: mdiShape,
}
